AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  TelegramApiKey:
    Type: String
  BucketName:
    Type: String
    Default: web-observer-bucket
  ContentDynamoTableName:
    Type: String
    Default: ObserverTraces
  FlowDynamoTableName:
    Type: String
    Default: ObserverBotFlow
  

##########################################################################
#  Global values that are applied to all resources                       #
##########################################################################
Globals:
  Function:
    MemorySize: 512
    Architectures: ["arm64"]
    Runtime: provided.al2
    Timeout: 29
    Layers:
      - !Sub arn:aws:lambda:eu-west-1:580247275435:layer:LambdaInsightsExtension-Arm64:2

Resources:
##########################################################################
#   Lambda Functions                                                     #
##########################################################################
  ObserverBotHandlerLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/web-observer-bot-${AWS::StackName}"

  ObserverBotHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub web-observer-bot-${AWS::StackName}
      FunctionUrlConfig:
        AuthType: NONE
      CodeUri: ../build/bot.zip
      Handler: main
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ContentDynamoTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowDynamoTableName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramApiKey
          FLOW_TABLE_NAME: !Ref FlowDynamoTableName
          CONTENT_TABLE_NAME: !Ref ContentDynamoTableName
    DependsOn:
      - ObserverBotHandlerLogs

  WebObserverTrackerLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/web-observer-${AWS::StackName}"

  WebObserverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub web-observer-${AWS::StackName}
      CodeUri: ../build/web-observer.zip
      Handler: main
      Timeout: 900
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ContentDynamoTableName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          FLOW_TABLE_NAME: !Ref FlowDynamoTableName
          CONTENT_TABLE_NAME: !Ref ContentDynamoTableName
          TELEGRAM_BOT_TOKEN: !Ref TelegramApiKey
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ObserverTriggerQueue.Arn
            BatchSize: 1
            Enabled: true
        20sDelaySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt 20sDelayTriggerQueue.Arn
            BatchSize: 1
            Enabled: true
        40sDelaySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt 40sDelayTriggerQueue.Arn
            BatchSize: 1
            Enabled: true
    DependsOn:
      - WebObserverTrackerLogs

##########################################################################
#   SQS Queues AND Scheduling                                            #
##########################################################################
  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: ObserverTriggerQueue
        - Ref: 20sDelayTriggerQueue
        - Ref: 40sDelayTriggerQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id: SchedulerSQSPolicy
        Statement:
          - Sid: PerMinuteAllowEventBridge
            Effect: Allow
            Action:
              - sqs:SendMessage
            Principal:
              Service: events.amazonaws.com
            Resource:
              Fn::GetAtt:
                - ObserverTriggerQueue
                - Arn
            Condition:
              ArnEquals: 
                "aws:SourceArn": !GetAtt PerMinuteSchedule.Arn
          - Sid: DelayAllowEventBridge
            Effect: Allow
            Action:
              - sqs:SendMessage
            Principal:
              Service: events.amazonaws.com
            Resource:
              Fn::GetAtt:
                - 20sDelayTriggerQueue
                - Arn
            Condition:
              ArnEquals: 
                "aws:SourceArn": !GetAtt PerMinuteSchedule.Arn
          - Sid: 40DelayAllowEventBridge
            Effect: Allow
            Action:
              - sqs:SendMessage
            Principal:
              Service: events.amazonaws.com
            Resource:
              Fn::GetAtt:
                - 40sDelayTriggerQueue
                - Arn
            Condition:
              ArnEquals: 
                "aws:SourceArn": !GetAtt PerMinuteSchedule.Arn

  ObserverTriggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub observer-trigger-sqs
      MessageRetentionPeriod: 120
      VisibilityTimeout: 900
  
  20sDelayTriggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 20sDelay-trigger-sqs
      MessageRetentionPeriod: 120
      VisibilityTimeout: 900
      DelaySeconds: 20

  40sDelayTriggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 40sDelay-trigger-sqs
      MessageRetentionPeriod: 120
      VisibilityTimeout: 900
      DelaySeconds: 40
  
  PerMinuteSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: observer-schedule-per-minute
      Description: Sends a message to the queue every minute
      ScheduleExpression: "cron(* * * * ? *)"
      Targets:
        - Arn: !GetAtt ObserverTriggerQueue.Arn
          Id: my-target-id
          Input: '{"message": "Run it"}'
        # - Arn: !GetAtt 20sDelayTriggerQueue.Arn
        #   Id: my-target-id-2
        #   Input: '{"message": "Run it"}'
        # - Arn: !GetAtt 40sDelayTriggerQueue.Arn
        #   Id: my-target-id-3
        #   Input: '{"message": "Run it"}'

##########################################################################
#   DynamoDb Tables                                                      #
##########################################################################
  ObserverTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ContentDynamoTableName
      AttributeDefinitions:
        - AttributeName: URL
          AttributeType: S
        - AttributeName: ChatID
          AttributeType: N
        - AttributeName: IsActive
          AttributeType: S
      KeySchema:
        - AttributeName: URL
          KeyType: HASH
        - AttributeName: ChatID
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ChatID-index
          KeySchema:
            - AttributeName: ChatID
              KeyType: HASH
            - AttributeName: URL
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        - IndexName: IsActive-index
          KeySchema:
            - AttributeName: IsActive
              KeyType: HASH
            - AttributeName: ChatID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  BotFlowTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FlowDynamoTableName
      AttributeDefinitions:
        - AttributeName: ChatID
          AttributeType: N
      KeySchema:
        - AttributeName: ChatID
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

##########################################################################
#   S3 Bucket                                                            #
##########################################################################
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteLifeCyclePolicy
            Status: Enabled
            ExpirationInDays: 30

Outputs:
  InputBucket:
    Value: 
      Ref: InputBucket
    Export: 
      Name: !Sub observer-bucket-${AWS::StackName}
  ObserverTable:
    Value: 
      Ref: ObserverTable
    Export: 
      Name: !Sub observer-table-${AWS::StackName}
