# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

on:
  workflow_dispatch:

jobs:
  DeploymentBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: SAM
      run: sam --version

    - name: Build
      run: make build

    - name: Persist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: checked-out-code
        path: .

  Deploy:
    runs-on: ubuntu-latest
    needs: DeploymentBuild
    steps:
    - name: Restore checkout
      uses: actions/download-artifact@v4
      with:
        name: checked-out-code

    - name: Deploy
      env:
        TELEGRAMAPIKEY: ${{ secrets.TELEGRAMAPIKEY }}
      run: sam deploy --no-confirm-changeset --capabilities CAPABILITY_NAMED_IAM --region eu-west-1 --stack-name web-observer-dev --s3-bucket aws-sam-observer-deployment --template-file ./deployment/observer.yml --parameter-overrides ParameterKey=TelegramApiKey,ParameterValue=$TELEGRAMAPIKEY
