# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches:
      - "master"
      - "feature/*"
  pull_request:
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Test
      run: make test
